### ISSUE TITLE
[24년 1월 4주차]

### ISSUE THREAD

**Issue by 2UJ1N** [CS-Study-crew/2024-CS-Study#5]
일시: 2024-01-25 (목) 10시~12시 (2h)
장소: 서울시 청년 일자리센터 일자리카페

**Comment by 2UJ1N** [comment]
### ✔️ To Do
`자기소개서`
- [ ] 경험 정리
- [ ] 피드백 반영해서 기본 이력서 수정하기
- [ ] 피드백 반영해서 삼성 자기소개서 수정하기

`자료구조`
- [ ] 각자 맡은 주제에 관해 발표 준비

- ⭐김예지 - `벡터` `트리`
- 🍀나지현 - `스택` `큐`
- ❄️노소희 - `연결리스트` `배열`
- 🎀이유진- `그래프` `힙`

**Comment by 2UJ1N** [comment]
### 🔜 Task

`자기소개서`
1. 경험 정리
2. 피드백 반영해서 기본 이력서 수정하기
3. 피드백 반영해서 삼성 자기소개서 수정하기

`CS 스터디`
1. Notion에 기록한 내용 Github에 .md 파일로 업로드하기
2. 각자 맡은 주제에 대해 발표 준비
**자료구조**
- ⭐김예지 - `트라이` 
- 🍀나지현 - `셋` `해쉬`
- ❄️노소희 - `우선순위 큐` `맵`
- 🎀이유진- `B-Tree & B+Tree`

**알고리즘**
- ⭐김예지 - `병합 정렬` `힙 정렬`
- 🍀나지현 - `삽입 정렬` `퀵 정렬`
- ❄️노소희 - `기수 정렬` `계수 정렬`
- 🎀이유진- `거품 정렬` `선택 정렬`
