### ISSUE TITLE
[24년 2월 1주차]

### ISSUE THREAD

**Issue by 2UJ1N** [CS-Study-crew/2024-CS-Study#6]
일시: 2024-02-01 (목) 10시~12시 (2h)
장소: 서울시 청년 일자리센터 일자리카페

**Comment by 2UJ1N** [comment]
🔜 Task
자기소개서

피드백 반영해서 공통항목 수정하기
1. 보유 역량
2. 자신을 어필할 수 있는 내용
희망 기업 셀렉하기

CS 스터디

Notion에 기록한 내용 Github에 .md 파일로 업로드하기
이번 주 발표 주제와 관련해서 면접 질문 (최대 5개) 업로드하기
각자 맡은 주제에 대해 발표 준비

**Comment by 2UJ1N** [comment]
### ✔️ To Do
`자기소개서`
- [x] 자소서 공통 항목 작성하기

`자료구조`
- [x] 각자 맡은 주제에 대해 발표 준비

- ⭐김예지 - `트라이`
- 🍀나지현 - `셋` `해시`
- ❄️노소희 - `맵` `우선순위 큐`
- 🎀이유진- `B Tree` 

`알고리즘`
- [x] 각자 맡은 주제에 대해 발표 준비

- ⭐김예지 - `병합 정렬` `힙 정렬`
- 🍀나지현 - `삽입 정렬` `퀵 정렬`
- ❄️노소희 - `기수 정렬` `계수 정렬`
- 🎀이유진- `버블 정렬` `선택 정렬`

**Comment by 2UJ1N** [comment]
# 🔜 Task
`자기소개서`

피드백 반영해서 공통항목 수정하기
1. 보유 역량
2. 자신을 어필할 수 있는 내용

희망 기업 셀렉하기

CS 스터디

Notion에 기록한 내용 Github에 .md 파일로 업로드하기
이번 주 발표 주제와 관련해서 면접 질문 (최대 5개) 업로드하기
각자 맡은 주제에 대해 발표 준비
